[package]
name = "cmd"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
thiserror = "1.0.50"
crossbeam = "0.8.2"
signal-hook = "0.3.17"
crossbeam-channel = "0.5.9"

[dev-dependencies]
simple_logger = "4.3.0"
ctrlc = "3.4.1"
